### ISSUE TITLE
Novel `std` definitions

### ISSUE THREAD

**Issue by johnmcfarlane** [BobSteagall/wg21#1]
Reading [paragraph 1 of [namespace.std]](http://eel.is/c++draft/namespace.std#1), one might conclude that any program using this library is undefined:

> Unless otherwise specified, the behavior of a C++ program is undefined if it adds declarations or definitions to namespace `std` or to a namespace within namespace `std`.

That looks a lot like what [this line](https://github.com/BobSteagall/wg21/blob/master/linear_algebra/code/matrix.hpp#L6) does, for instance.

In practice, the code is likely to work just fine. However, it might put people off trying out the library knowing that there is technically no way of using it in a standards-compliant program.

**Comment by BobSteagall** [comment]
Yes, we're aware of that, and know that it will very likely have to change.  This draft is really for thinking about a big-picture design, and then fixing up other details later (like the namespace, bikeshedding the names, constexpr, etc.)
