### ISSUE TITLE
cmake fails on windows 10

### ISSUE THREAD

**Issue by wgreene310** [BobSteagall/wg21#44]
Using the cmake gui version 3.15.3, I get the following errors during configuration:

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Performing download step (git clone) for 'mdspan-populate'
  Cloning into 'mdspan-src'...
  fatal: unable to access 'https://github.com/kokkos/mdspan.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  Cloning into 'mdspan-src'...
  fatal: unable to access 'https://github.com/kokkos/mdspan.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  Cloning into 'mdspan-src'...
  fatal: unable to access 'https://github.com/kokkos/mdspan.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  -- Had to git clone more than once:
  CMake Error at mdspan-subbuild/mdspan-populate-prefix/tmp/mdspan-populate-gitclone.cmake:31 (message):
            3 times.
    Failed to clone repository: 'https://github.com/kokkos/mdspan.git'
  
  
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 1. [C:\temp\Projects\cpp_standard_linear_algebra\_deps\mdspan-subbuild\mdspan-populate.vcxproj]

CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FetchContent.cmake:915 (message):
  Build step for mdspan failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FetchContent.cmake:1006 (__FetchContent_directPopulate)
  CMakeLists.txt:13 (FetchContent_Populate)

**Comment by Twon** [comment]
I've attempted to recreate this issue without any luck on Windows 10 64-bit.  I appears that an underlying git clone call fails (internally to the CMake function FetchContent_Populate).  Can you call "git clone https://github.com/kokkos/mdspan.git" and clone the mdspan repository locally without issue?

**Comment by wgreene310** [comment]
> Can you call "git clone https://github.com/kokkos/mdspan.git" and clone
the mdspan repository locally without issue?
Yes, I can do that with no problems.

Since I submitted that bug report, I tracked down the immediate problem as
cmake not finding the right version of git. I should have updated
my problem report; sorry!

But even with that problem resolved, I have run into another problem with
FetchContent_Populate that I have not been able to resolve. I'm pasting the
cmake output below. Note, that I have added some debug print statements to
some of the cmake files to help in my debugging:
----------------------------------------------------------------------------------------------------------------------------------------------

&&&&& GIT_EXECUTABLE=C:/Program Files/Git/bin/git.exe

Found Git: C:/Program Files/Git/bin/git.exe (found version
"2.26.2.windows.1")

$$$ GIT_EXECUTABLE=C:/Program Files/Git/bin/git.exe

Git found: C:/Program Files/Git/bin/git.exe

Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Checking Build System
Creating directories for 'mdspan-populate'
Building Custom Rule
C:/temp/Projects/cpp_standard_linear_algebra_xxx/_deps/mdspan-subbuild/CMakeLists.txt
Performing download step (git clone) for 'mdspan-populate'
-- Avoiding repeated git clone, stamp file is up to date:
'C:/temp/Projects/cpp_standard_linear_algebra_xxx/_deps/mdspan-subbuild/mdspan-populate-prefix/src/mdspan-populate-stamp/mdspan-populate-gitinfo.txt'
Performing update step for 'mdspan-populate'
fatal: not a git repository (or any of the parent directories): .git
CMake Error at
C:/temp/Projects/cpp_standard_linear_algebra_xxx/_deps/mdspan-subbuild/mdspan-populate-prefix/tmp/mdspan-populate-gitupdate.cmake:10
(message):
Failed to get the hash for HEAD


C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5):
error MSB6006: "cmd.exe" exited with code 1.
[C:\temp\Projects\cpp_standard_linear_algebra_xxx\_deps\mdspan-subbuild\mdspan-populate.vcxproj]

CMake Error at C:/Program
Files/CMake/share/cmake-3.17/Modules/FetchContent.cmake:913 (message):
Build step for mdspan failed: 1
Call Stack (most recent call first):
C:/Program Files/CMake/share/cmake-3.17/Modules/FetchContent.cmake:1004
(__FetchContent_directPopulate)
CMakeLists.txt:22 (FetchContent_Populate)


----------------------------------------------------------------------------------------------------------------

**Comment by Twon** [comment]
Hey, apologies for the delay in coming back to you, there has been a number of pressing issue to resolve for the just release v0.7.0 revision of Linear Algebra.

So looking at the errors you've posted it looks like the failures are happening internally within CMake.  It's not really practical to remotely try and debug this via github issues, so I might suggest you try a minimal reproduction case for the issue, I've actually provided an example of this on the mdspan github issue tracker: https://github.com/kokkos/mdspan/issues/28

If you try setting up a folder with the main.cpp and CMakeLists.txt that I've provided here then you can isolate if the issue is within CMake or specific to the wg21 repo.  Given we have all builds passing across Windows, Linux and MacOS at the moment I suspect it is something specific to your environment. But testing the reproduction case I've outlined should show that conclusively.

If you can let us know the outcome of that I'll try and assist/advise further where I can. Can I ask what is your use-case for the Linear Algebra project?  Because if you just want to use the Linear Algebra project there are pre-built Conan packages available which would allow you to sidestep the requirement to build at all.

**Comment by Twon** [comment]
Please note there is now a reproduction case you can just clone here which should be suitable isolate the issue: https://github.com/Twon/mdspan_macos_include_order_issue

**Comment by wgreene310** [comment]
OK, thanks.

  I am running cmake 3.17.2 on windows 10.

I did the following:
1. Start git bash shell.
2. git --version
git version 2.26.2.windows.1
3. Run cmake gui: C:/Progra~1/CMake/bin/cmake-gui.exe
4. Enter these directories in the gui:
C:/wgreene/tests/c++/cmake_test_cpp_linear_algebra/mdspan_macos_include_order_issue
C:/temp/Projects/mdspan_macos_include_order_issue
5. Push Configure button:

I get the following errors:

Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(467,5):
warning MSB8029: The Intermediate directory or Output directory cannot
reside under the Temporary directory as it could lead to issues with
incremental build.
[C:\temp\Projects\mdspan_macos_include_order_issue\_deps\mdspan-subbuild\ZERO_CHECK.vcxproj]
Checking Build System
C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(467,5):
warning MSB8029: The Intermediate directory or Output directory cannot
reside under the Temporary directory as it could lead to issues with
incremental build.
[C:\temp\Projects\mdspan_macos_include_order_issue\_deps\mdspan-subbuild\mdspan-populate.vcxproj]
Creating directories for 'mdspan-populate'
Building Custom Rule
C:/temp/Projects/mdspan_macos_include_order_issue/_deps/mdspan-subbuild/CMakeLists.txt
Performing download step (git clone) for 'mdspan-populate'
-- Avoiding repeated git clone, stamp file is up to date:
'C:/temp/Projects/mdspan_macos_include_order_issue/_deps/mdspan-subbuild/mdspan-populate-prefix/src/mdspan-populate-stamp/mdspan-populate-gitinfo.txt'
Performing update step for 'mdspan-populate'
fatal: not a git repository (or any of the parent directories): .git
CMake Error at
C:/temp/Projects/mdspan_macos_include_order_issue/_deps/mdspan-subbuild/mdspan-populate-prefix/tmp/mdspan-populate-gitupdate.cmake:10
(message):
Failed to get the hash for HEAD


C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5):
error MSB6006: "cmd.exe" exited with code 1.
[C:\temp\Projects\mdspan_macos_include_order_issue\_deps\mdspan-subbuild\mdspan-populate.vcxproj]

CMake Error at C:/Program
Files/CMake/share/cmake-3.17/Modules/FetchContent.cmake:913 (message):
Build step for mdspan failed: 1
Call Stack (most recent call first):
C:/Program Files/CMake/share/cmake-3.17/Modules/FetchContent.cmake:1004
(__FetchContent_directPopulate)
C:/Program Files/CMake/share/cmake-3.17/Modules/FetchContent.cmake:1045
(FetchContent_Populate)
CMakeLists.txt:10 (FetchContent_MakeAvailable)

**Comment by Twon** [comment]
Apologies I missed the follow up comment on this.  Given its over a year ago now I'm going to close.  If you still have an issue then please reopen or raise a new issue.
