### ISSUE TITLE
linear_algebra/0.6.0@public-conan/testing fails to build

### ISSUE THREAD

**Issue by mpusz** [BobSteagall/wg21#45]
The latest Conan version of 0.6.0 does not build. A list of errors can be found here: https://travis-ci.com/github/mpusz/units/builds/164049972#L804.

**Comment by mpusz** [comment]
BTW, could you please set the Conan build process to build unit tests only in CONAN_RUN_TESTS=True? People using your package should not wait for all tests to build and run (and also to download and build dependencies needed to compile those tests).

**Comment by Twon** [comment]
Yes, that makes sense.  That option has now been added on this pull request: https://github.com/BobSteagall/wg21/pull/46

**Comment by Twon** [comment]
Requested changed now add. The testing channel should now be building successfully again, and there are releases on the stable channel available for v0.6.0 and v0.7.0: https://github.com/BobSteagall/wg21/releases
