### ISSUE TITLE
is this proposal still on track for c++23?

### ISSUE THREAD

**Issue by RiccardoRossi** [BobSteagall/wg21#60]
Just to clarify, i think that the proposed library would be extremely useful, and i am really hoping it will be envtually standardized...just wanted to know if this is still being considered in the standardization process.

**Comment by hatcat** [comment]
This proposal is still very much alive and kicking. This weekend we are drafting revision seven of the proposal, and we hope to have something for the December mailing. Getting it into C++23 is a different matter: without regular face to face meetings everything is taking place online in reduced circumstances. A colleague from the Library Working Group suggested that the queue was probably full for C++23, so priorities need to be modified if the finished article is to make it for the next standard. Modifying priorities is simply a matter of contacting your national body chair (and getting your colleagues to do the same) and requesting that they prioritise this proposal for inclusion in C++23. They work for you.

There are other ways you can help: review the code, use it, write customisations for various parts, try it out on differen compilers, feedback is always welcome!

**Comment by RiccardoRossi** [comment]
ok perfect.
we will be looking into it and i will also tell to my colleagues. thx for the quick answer
