### ISSUE TITLE
Update to use mdspan (not basic_mdspan)

### ISSUE THREAD

**Issue by Twon** [BobSteagall/wg21#70]
The specification of mdspan has been updated to remove the basic_mdspan identifier in favor of the mdspan.  Because of this we've had to pin to an earlier version of the mdspan repo here: https://github.com/BobSteagall/wg21/blob/4b39067496f3a6401f6c76e965703de20c6622d7/CMakeLists.txt#L24

But this was only intended as a temporary work around, and required updating the source to address.  All usage of MDspan should be updated the change merged to active branched (`r7y`)

**Comment by BobSteagall** [comment]
done in r7z
